### ISSUE TITLE
What about client env file?

### ISSUE THREAD

**Issue by Yobro7292** [rammyblog/MERN-Admin-Dashboard#7]
What are the values in the env file of the client?

**Comment by malekkadri** [comment]
MONGODB_URI=mongodb+srv://username:password@cluster0.tw7fxff.mongodb.net/databaseName?retryWrites=true&w=majority
TOKEN_SECRET = secret
BASE_URL=http://localhost:8002/api/
port=8002

**Comment by Yobro7292** [comment]
Thanks a lot.
